# Generated by Django 6.0.1 on 2026-01-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("orgs", "0003_role_alter_invitation_role_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("TEXTAREA", "Long Text"),
                            ("SELECT", "Dropdown"),
                            ("RADIO", "Radio Buttons"),
                            ("CHECKBOX", "Checkbox"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone Number"),
                            ("DATE", "Date"),
                            ("NUMBER", "Number"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("per_ticket", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organization", "state"], name="events_even_organiz_a42c57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_even_slug_30eb0f_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_public", "state"], name="events_even_is_publ_af3ea5_idx"
            ),
        ),
        migrations.AddField(
            model_name="checkoutquestion",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_questions",
                to="events.event",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutquestion",
            index=models.Index(
                fields=["event", "order"], name="events_chec_event_i_8ab4e1_idx"
            ),
        ),
    ]
