# Generated by Django 6.0.1 on 2026-01-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_checkoutquestion_event_is_public_event_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('heading_font', models.CharField(default='system-ui', max_length=100)),
                ('body_font', models.CharField(default='system-ui', max_length=100)),
                ('layout_template', models.CharField(choices=[('DEFAULT', 'Default'), ('MINIMAL', 'Minimal'), ('FULL_WIDTH', 'Full Width'), ('CENTERED', 'Centered')], default='DEFAULT', max_length=20)),
                ('hero_image', models.ImageField(blank=True, upload_to='event_heroes/')),
                ('logo', models.ImageField(blank=True, upload_to='event_logos/')),
                ('custom_css', models.TextField(blank=True)),
                ('hide_reckot_branding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='events.event')),
            ],
        ),
    ]
