# Generated by Django 6.0.1 on 2026-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_address_line_2_event_city_event_contact_email_and_more'),
        ('orgs', '0004_organization_description_organization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feature_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'feature_order'], name='events_even_is_feat_44d40f_idx'),
        ),
    ]
