# Generated by Django 6.0.1 on 2026-01-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_pay_per_use_accepted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventflyerconfig',
            name='template_change_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
