# Generated by Django 6.0.1 on 2026-01-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_allow_blank_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventflyerconfig",
            name="photo_bg_color",
            field=models.CharField(default="rgba(0,0,0,0)", max_length=30),
        ),
        migrations.AddField(
            model_name="flyertextfield",
            name="bg_color",
            field=models.CharField(default="rgba(0,0,0,0.3)", max_length=30),
        ),
    ]
