# Generated by Django 6.0.1 on 2026-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_add_email_phone_to_flyer_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticket_prefix",
            field=models.CharField(
                default="RECK",
                help_text="3-4 letter prefix for ticket codes (e.g., RECK, EVNT)",
                max_length=4,
            ),
        ),
    ]
