# Generated by Django 6.0.1 on 2026-01-31 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_ticket_prefix'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flyergeneration',
            name='unique_flyer_per_email',
        ),
        migrations.RemoveConstraint(
            model_name='flyergeneration',
            name='unique_flyer_per_phone',
        ),
    ]
