from django.urls import path

from apps.cfp.views import organizer, public, speaker

app_name = "cfp"

urlpatterns = [
    path(
        "dashboard/",
        organizer.CFPDashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "speakers/",
        organizer.SpeakerManagementView.as_view(),
        name="speakers",
    ),
    path(
        "speakers/export/",
        organizer.ExportSpeakersView.as_view(),
        name="export_speakers",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/",
        public.PublicCFPView.as_view(),
        name="public_cfp",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/schedule/",
        public.PublicScheduleView.as_view(),
        name="public_schedule",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/schedule/<int:id>/",
        public.PublicSessionDetailView.as_view(),
        name="public_session",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/speakers/",
        public.PublicSpeakerListView.as_view(),
        name="public_speakers",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/submit/",
        speaker.CFPSubmitView.as_view(),
        name="submit_proposal",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/proposals/",
        speaker.SpeakerProposalsView.as_view(),
        name="speaker_proposals",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/proposals/<int:id>/",
        speaker.ProposalEditView.as_view(),
        name="proposal_edit",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/proposals/<int:id>/confirm/",
        speaker.ProposalConfirmView.as_view(),
        name="proposal_confirm",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/proposals/<int:id>/withdraw/",
        speaker.ProposalWithdrawView.as_view(),
        name="proposal_withdraw",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/cfp/profile/",
        speaker.SpeakerProfileView.as_view(),
        name="speaker_profile",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/",
        organizer.CFPConfigView.as_view(),
        name="cfp_config",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/formats/",
        organizer.SessionFormatManageView.as_view(),
        name="session_formats",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/tracks/",
        organizer.TrackManageView.as_view(),
        name="tracks",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/questions/",
        organizer.CFPQuestionsView.as_view(),
        name="cfp_questions",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/proposals/",
        organizer.ProposalListView.as_view(),
        name="proposals_list",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/proposals/<int:id>/",
        organizer.ProposalDetailView.as_view(),
        name="proposal_detail",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/proposals/<int:id>/review/",
        organizer.ProposalReviewView.as_view(),
        name="proposal_review",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/proposals/<int:id>/decide/",
        organizer.ProposalDecideView.as_view(),
        name="proposal_decide",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/proposals/bulk-action/",
        organizer.BulkActionView.as_view(),
        name="bulk_action",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/proposals/export/",
        organizer.ExportProposalsView.as_view(),
        name="export_proposals",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/cfp/analytics/",
        organizer.CFPAnalyticsView.as_view(),
        name="cfp_analytics",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/schedule/",
        organizer.ScheduleBuilderView.as_view(),
        name="schedule_builder",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/schedule/update/",
        organizer.ScheduleUpdateView.as_view(),
        name="schedule_update",
    ),
    path(
        "<slug:org_slug>/<slug:event_slug>/manage/schedule/<int:id>/edit/",
        organizer.SessionEditView.as_view(),
        name="session_edit",
    ),
]
