# Generated by Django 6.0.1 on 2026-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecampaign',
            name='recipient_filter',
            field=models.CharField(choices=[('ALL', 'All Attendees'), ('TICKET_TYPE', 'By Ticket Type'), ('CHECKED_IN', 'Checked In Only'), ('NOT_CHECKED_IN', 'Not Checked In'), ('ALL_SPEAKERS', 'All Speakers'), ('ACCEPTED_SPEAKERS', 'Accepted Speakers')], default='ALL', max_length=20),
        ),
    ]
