# Generated by Django 6.0.1 on 2026-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_email_verified_user_phone_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_features_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
