# Generated by Django 6.0.1 on 2026-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ai_features_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
