# Generated by Django 6.0.1 on 2026-02-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_ai_default_to_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
