# Generated by Django 6.0.1 on 2026-02-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_mode',
            field=models.CharField(choices=[('ATTENDEE', 'Attendee'), ('SPEAKER', 'Speaker'), ('ORGANIZER', 'Organizer')], default='ATTENDEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TICKET_PURCHASE', 'Ticket Purchase'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_PROCESSED', 'Refund Processed'), ('EVENT_UPDATE', 'Event Update'), ('EVENT_CANCELLED', 'Event Cancelled'), ('SALE_MADE', 'Sale Made'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_ACCEPTED', 'Proposal Accepted'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('PROPOSAL_WAITLISTED', 'Proposal Waitlisted'), ('CFP_OPENED', 'CFP Opened')], max_length=25),
        ),
    ]
