# Generated by Django 6.0.1 on 2026-01-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0003_role_alter_invitation_role_alter_membership_role"),
        ("payments", "0002_refund_refundauditlog_and_more"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("XAF", "Central African CFA Franc"),
                    ("XOF", "West African CFA Franc"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("NGN", "Nigerian Naira"),
                    ("GHS", "Ghanaian Cedi"),
                    ("UGX", "Ugandan Shilling"),
                ],
                default="XAF",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("MTN_MOMO", "MTN Mobile Money"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("STRIPE", "Stripe"),
                    ("PAYPAL", "PayPal"),
                    ("OFFLINE", "Offline Payment"),
                ],
                default="MTN_MOMO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="redirect_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="external_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="OfflinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_description", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True)),
                (
                    "proof_file",
                    models.FileField(blank=True, upload_to="payment_proofs/"),
                ),
                ("proof_notes", models.TextField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_details",
                        to="payments.payment",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("MTN_MOMO", "MTN Mobile Money"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("OFFLINE", "Offline Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("supported_currencies", models.JSONField(default=list)),
                (
                    "service_fee_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage"),
                            ("BOTH", "Fixed + Percentage"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "service_fee_fixed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "service_fee_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_gateways",
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentgatewayconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider"], name="payments_pa_provide_502c98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinepayment",
            index=models.Index(
                fields=["verification_status"], name="payments_of_verific_06c826_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewayconfig",
            index=models.Index(
                fields=["organization", "is_active"],
                name="payments_pa_organiz_d00172_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentgatewayconfig",
            unique_together={("organization", "provider")},
        ),
    ]
