# Generated by Django 6.0.1 on 2026-01-30 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0007_organization_plans"),
        ("payments", "0005_add_invoice_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gateway_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "Central African CFA Franc"),
                            ("XOF", "West African CFA Franc"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("NGN", "Nigerian Naira"),
                            ("GHS", "Ghanaian Cedi"),
                            ("UGX", "Ugandan Shilling"),
                        ],
                        default="XAF",
                        max_length=3,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("CAMPAY", "Campay"),
                            ("PAWAPAY", "PawaPay"),
                            ("FLUTTERWAVE", "Flutterwave"),
                            ("MTN_MOMO", "MTN Mobile Money"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("OFFLINE", "Offline Payment"),
                        ],
                        default="CAMPAY",
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="orgs.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="payments_wi_referen_3516ee_idx"
                    ),
                    models.Index(
                        fields=["external_reference"],
                        name="payments_wi_externa_ef9423_idx",
                    ),
                    models.Index(
                        fields=["organization"], name="payments_wi_organiz_d8b67a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_wi_status_c33804_idx"
                    ),
                ],
            },
        ),
    ]
