# Generated by Django 6.0.1 on 2026-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_performance_indexes'),
        ('payments', '0006_withdrawal'),
    ]

    operations = [
    ]
