# Generated by Django 6.0.1 on 2026-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_remove_payment_payment_status_expires_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
