# Generated by Django 6.0.1 on 2026-02-09 14:16

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_status'),
        ('tickets', '0007_booking_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='invoices/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.core.validators.validate_pdf_file_size]),
        ),
        migrations.AlterField(
            model_name='offlinepayment',
            name='proof_file',
            field=models.FileField(blank=True, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), apps.core.validators.validate_document_file_size]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('external_reference',), name='unique_external_reference_when_set'),
        ),
    ]
