# Generated by Django 6.0.1 on 2026-01-28 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
