# Generated by Django 6.0.1 on 2026-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_change_ticket_code_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_method',
            field=models.CharField(choices=[('EMAIL_ALL', 'Email me all tickets'), ('EMAIL_INDIVIDUALLY', 'Email tickets individually')], default='EMAIL_ALL', help_text='How tickets should be delivered to recipients', max_length=20),
        ),
    ]
