# Generated by Django 6.0.1 on 2026-02-09 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0018_eventcategory_event_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallForProposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('REVIEWING', 'Reviewing'), ('DECIDED', 'Decided')], default='DRAFT', max_length=20)),
                ('title', models.CharField(default='Call for proposals', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Guidelines and what you are looking for in proposals')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('max_submissions_per_speaker', models.PositiveIntegerField(default=3)),
                ('anonymous_review', models.BooleanField(default=True, help_text='Hide speaker information from reviewers')),
                ('allow_edits_after_submit', models.BooleanField(default=True)),
                ('notify_on_submission', models.BooleanField(default=True, help_text='Email organizers when a new proposal is submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cfp', to='events.event')),
            ],
            options={
                'verbose_name': 'Call for proposals',
                'verbose_name_plural': 'Calls for proposals',
            },
        ),
        migrations.CreateModel(
            name='CFPQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Text area'), ('SELECT', 'Select'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('NUMBER', 'Number')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select, radio, or checkbox fields')),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('cfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cfp.callforproposals')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(help_text='Short public-facing summary of your proposal')),
                ('description', models.TextField(help_text='Detailed description for reviewers')),
                ('outline', models.TextField(blank=True, help_text='Talk outline or structure')),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ALL', 'All levels')], default='ALL', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('WITHDRAWN', 'Withdrawn'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('speaker_notes', models.TextField(blank=True, help_text='Private notes to organizers')),
                ('organizer_notes', models.TextField(blank=True, help_text='Internal notes visible only to organizers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='cfp.callforproposals')),
                ('co_speakers', models.ManyToManyField(blank=True, related_name='co_proposals', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='cfp.proposal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cfp.cfpquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('relevance_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('speaker_score', models.PositiveSmallIntegerField(blank=True, help_text='Hidden when anonymous review is enabled', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_abstained', models.BooleanField(default=False, help_text='Reviewer has a conflict of interest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cfp.proposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfp_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_formats', to='events.event')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='session_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='cfp.sessionformat'),
        ),
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='speaker_photos/')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('travel_assistance', models.BooleanField(default=False)),
                ('accommodation_needed', models.BooleanField(default=False)),
                ('dietary_requirements', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Private notes visible only to organizers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profiles', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#09090b', help_text='Hex color code for track badge', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_speakers', models.ManyToManyField(blank=True, related_name='co_sessions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='cfp.proposal')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('session_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cfp.sessionformat')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cfp.track')),
            ],
            options={
                'ordering': ['starts_at', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='cfp.track'),
        ),
        migrations.AddIndex(
            model_name='callforproposals',
            index=models.Index(fields=['status'], name='cfp_callfor_status_289243_idx'),
        ),
        migrations.AddIndex(
            model_name='callforproposals',
            index=models.Index(fields=['closes_at'], name='cfp_callfor_closes__82e2e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalquestionanswer',
            unique_together={('proposal', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('proposal', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='speakerprofile',
            index=models.Index(fields=['user', 'event'], name='cfp_speaker_user_id_5bdab1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakerprofile',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['event', 'starts_at'], name='cfp_session_event_i_7479fd_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['event', 'track'], name='cfp_session_event_i_7eb88a_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['event', 'status'], name='cfp_session_event_i_ceefd2_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['cfp', 'status'], name='cfp_proposa_cfp_id_c551c0_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['speaker', 'status'], name='cfp_proposa_speaker_7ef15d_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['cfp', 'speaker'], name='cfp_proposa_cfp_id_8f2431_idx'),
        ),
    ]
