# Generated by Django 6.0.1 on 2026-02-09 14:16

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='speaker_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_file_size]),
        ),
    ]
