# Generated by Django 6.0.1 on 2026-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_alter_speakerprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom speaker data as key-value pairs'),
        ),
    ]
