# Generated by Django 6.0.1 on 2026-01-30 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("request_count", models.IntegerField(default=0)),
                ("daily_limit", models.IntegerField(default=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_rate_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="ai_airateli_user_id_c8d074_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, null=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CHAT", "Chat Message"),
                            ("GENERATE_DESCRIPTION", "Generate Description"),
                            ("GENERATE_IMAGE", "Generate Image"),
                            ("IMPROVE_TEXT", "Improve Text"),
                            ("TRANSLATE", "Translate"),
                            ("SUMMARIZE", "Summarize"),
                            ("INSIGHT", "Generate Insight"),
                            ("QUERY", "Database Query"),
                            ("VOICE_TO_EVENT", "Voice to Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "execution_time",
                    models.FloatField(help_text="Execution time in seconds"),
                ),
                ("models_accessed", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_aiusagel_user_id_679c78_idx",
                    ),
                    models.Index(
                        fields=["operation", "-created_at"],
                        name="ai_aiusagel_operati_4bf400_idx",
                    ),
                ],
            },
        ),
    ]
