# Generated by Django 6.0.1 on 2026-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_add_ai_usage_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagelog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("CHAT", "Chat Message"),
                    ("GENERATE_DESCRIPTION", "Generate Description"),
                    ("GENERATE_IMAGE", "Generate Image"),
                    ("IMPROVE_TEXT", "Improve Text"),
                    ("TRANSLATE", "Translate"),
                    ("SUMMARIZE", "Summarize"),
                    ("INSIGHT", "Generate Insight"),
                    ("QUERY", "Database Query"),
                    ("VOICE_TO_EVENT", "Voice to Event"),
                    ("VERIFY_EVENT", "Verify Event"),
                    ("PREDICT_SALES", "Predict Sales"),
                    ("OPTIMIZE_PRICING", "Optimize Pricing"),
                    ("MARKETING_STRATEGY", "Marketing Strategy"),
                ],
                max_length=50,
            ),
        ),
    ]
