# Generated by Django 6.0.1 on 2026-02-03 19:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0018_eventcategory_event_category_and_more'),
        ('orgs', '0008_organization_currency'),
        ('payments', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_processing_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('events_created', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Metrics',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('tickets_checked_in', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Metrics',
                'verbose_name_plural': 'Event Metrics',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_tickets_sold', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('active_events', models.IntegerField(default=0)),
                ('completed_events', models.IntegerField(default=0)),
                ('total_attendees', models.IntegerField(default=0)),
                ('average_ticket_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'Organization Metrics',
                'verbose_name_plural': 'Organization Metrics',
            },
        ),
        migrations.CreateModel(
            name='PaymentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gateway_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('net_amount_to_organizer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Metrics',
                'verbose_name_plural': 'Payment Metrics',
            },
        ),
    ]
