# Generated by Django 6.0.1 on 2026-02-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymetrics',
            name='payment_processing_fees',
        ),
        migrations.RemoveField(
            model_name='eventmetrics',
            name='payment_fees',
        ),
    ]
