# Generated by Django 6.0.1 on 2026-01-28 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("RSVP", "RSVPs"),
                            ("PAYMENTS", "Payments"),
                            ("CHECKINS", "Check-ins"),
                            ("SWAG", "Swag Collection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("EXCEL", "Excel")], max_length=10
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="exports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mask_emails", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "report_type"],
                        name="reports_rep_event_i_ef3310_idx",
                    )
                ],
            },
        ),
    ]
