# Generated by Django 6.0.1 on 2026-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_alter_reportexport_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportexport",
            name="format",
            field=models.CharField(
                choices=[
                    ("CSV", "CSV"),
                    ("EXCEL", "Excel"),
                    ("PDF", "PDF"),
                    ("JSON", "JSON"),
                ],
                max_length=10,
            ),
        ),
    ]
