# Generated by Django 6.0.1 on 2026-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_add_performance_indexes"),
        ("reports", "0004_alter_reportexport_format"),
    ]

    operations = []
